config/routes.rb
Rails.application.routes.draw do
  get 'main/login'
  post 'main/create'
  resources :scores
  resources :students
  get "students/:id/edit_score", to: "students#edit_score"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :scores, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def is_login?
            return session[:logged_in] == true
        end

        def must_be_logged_in
            if is_login?
                return true
            else
                redirect_to '/main/login' ,notice: 'login first!'
            end
        end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def login
  end
  def create
    u=User.where(username:params[:username]).first
    if u && u.authenticate(params[:password])
      redirect_to students_path
      session[:logged_in] =true
    else
      redirect_to main_login_path, notice: 'wrong login info'
    end

  end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :must_be_logged_in
  #before_action :set_score, only: %i[ show edit update destroy ]
  
  # GET /scores or /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to score_url(@score), notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to score_url(@score), notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:subject, :point, :grade, :student_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :must_be_logged_in, except: [:edit_score, :index]
  #before_action :set_student, only: %i[ show edit update destroy ]
  
  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def edit_score
      @id = params[:id].to_i
      @student = Student.find_by(id:@id)
      @sum = 0
      @max_score=@student.scores[0].point
      @max_subject=@student.scores[0].subject
      for @s in @student.scores
        @sum=@sum+@s.point.to_i
        if(@max_score<@s.point.to_i)
          @max_subject=@s.subject
        end
      end
      @avg=@sum/@student.scores.length.to_f
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :dob, :student_no, :class_year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lec07</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type,msg| %>
      <p>
      <%= msg %>
      </p>
      <% end %>
      <%= yield %>
  </body>
</html>

app/views/main/login.html.haml
%h1 Main#login
= form_with url:main_create_path, data: {turbo:false} do |f|
    =f.label:username
    =f.text_field:username
    %br
    =f.label:password
    =f.password_field:password
    =f.submit:OK

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :point, style: "display: block" %>
    <%= form.number_field :point %>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <%= form.text_field :grade %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>Subject:</strong>
    <%= score.subject %>
  </p>

  <p>
    <strong>Point:</strong>
    <%= score.point %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= score.grade %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= score.student_id %>
  </p>

</div>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Show this score", @score %> |
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Scores</h1>

<div id="scores">
  <% @scores.each do |score| %>
    <%= render score %>
    <p>
      <%= link_to "Show this score", score %>
    </p>
  <% end %>
</div>

<%= link_to "New score", new_score_path %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) %> |
  <%= link_to "Back to scores", scores_path %>

  <%= button_to "Destroy this score", @score, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.date_field :dob %>
  </div>

  <div>
    <%= form.label :student_no, style: "display: block" %>
    <%= form.text_field :student_no %>
  </div>

  <div>
    <%= form.label :class_year, style: "display: block" %>
    <%= form.number_field :class_year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= student.dob %>
  </p>

  <p>
    <strong>Student no:</strong>
    <%= student.student_no %>
  </p>

  <p>
    <strong>Class year:</strong>
    <%= student.class_year %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/edit_score.html.erb
<p> average score =
<%=
    @avg
    
%></p>
<p> max score subject =
<%=
    @max_subject
    
%></p>
<style>
table, th, td{
    border:1px solid black;
}
</style>
<table>
    <th>Subject</th>
    <th>Score</th>
    <th>Edit</th>
    <th>Delete</th>
    <% @student.scores.each do |s| %>
        <tr>
            <td><%= s.subject %></td>
            <td><%= s.point %></td>
            <td><%= link_to 'Edit', '/scores/'+s.id.to_s+'/edit'  %></td>
            <td><%= button_to "Delete", s, method: :delete %></td>
        </tr>
    <%end%>
</table>
<%=link_to 'NEW', '/scores/new'  %>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>